# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4b46e991fba03dde0fec9347720090d69e0fc8127a13914254dff4248c691569861bce323e46abbc6ceb8fddd2c7fcea67e40d0b3934e11513f4b9fa8710261

test:
  secret_key_base: af7087df4f078039a0b6b3c1161094468104f0665b7da26fa670c789903320ff5427d8ce648d4709211f74e73a1942647e6a08ed767760a12d0c5017c87b0938

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
